TABLE TipoUsuario{
    Id INT AUTOINCREMENT PRIMARY KEY,
    NomeTipo VARCHAR(100) NOT NULL
}

TABLE Usuario{
    Id INT AUTOINCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Sobrenome VARCHAR(150) NOT NULL,
    CPF VARCHAR(11) NULL UNIQUE,
    CNPJ VARCHAR(20) NULL UNIQUE,
    NomeEmpresa VARCHAR(256) NULL,
    Email VARCHAR(256) NOT NULL UNIQUE,
    Senha VARCHAR(100) NOT NULL,
    Id_TipoUsuario REFERENCES ('Id') FROM TipoUsuario ON DELETE CASCADE ON UPDATE CASCADE 
}

TABLE Telefone{
    Id INT AUTOINCREMENT PRIMARY KEY,
    DDD CHAR (3) NOT NULL,
    Telefone VARCHAR(9) NOT NULL UNIQUE,
    Id_Usuario REFERENCES ('Id') FROM Usuario ON DELETE CASCADE ON UPDATE CASCADE 
}

TABLE Endereco{
    Id INT AUTOINCREMENT PRIMARY KEY,
    Pais VARCHAR (100) NOT NULL,
    Estado VARCHAR (100) NOT NULL,
    Cidade VARCHAR (100) NOT NULL,
    Bairro VARCHAR (100) NOT NULL,
    Rua VARCHAR (100) NOT NULL,
    Numero VARCHAR (100) NOT NULL,
    Complemento VARCHAR (100) NOT NULL,
    Id_Usuario REFERENCES ('Id') FROM Usuario ON DELETE CASCADE ON UPDATE CASCADE 
}

TABLE Conta{
    Id INT AUTOINCREMENT PRIMARY KEY,
    NumeroDaConta INTEGER NOT NULL UNIQUE,
    DataDeCadastro DATE NOT NULL,
    Saldo DECIMAL NULL,
    LimiteDoUsuario DECIMAL NOT NULL,
    Id_Usuario REFERENCES ('Id') FROM Usuario ON DELETE CASCADE ON UPDATE CASCADE 
}