// <auto-generated />
namespace SistemaBancario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2210Joaov2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2210Joaov2));
        
        string IMigrationMetadata.Id
        {
            get { return "202110221905454_2210Joaov2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
