// <auto-generated />
namespace SistemaBancario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2210Joao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2210Joao));
        
        string IMigrationMetadata.Id
        {
            get { return "202110221902214_2210Joao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
